name: Check Taylor Swift Site Hash

on:
  workflow_dispatch:   # allows manual run
  schedule:
    - cron: "* * * * *"   # runs every minute (UTC)

jobs:
  check-hash:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo with credentials to allow push
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Important for pushing changes

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Step 3: Install requests
      - name: Install requests
        run: pip install requests

      # Step 4: Run Python script
      - name: Run hash check
        run: python job.py

      # Step 5: Commit updated hash file if changed
      - name: Commit updated hash.txt
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add hash.txt
          git diff-index --quiet HEAD || git commit -m "Update hash.txt"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
