name: Check Taylor Swift Site Hash

on:
  workflow_dispatch:
  schedule:
    - cron: "* * * * *"

jobs:
  check-hash:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Allows the runner to push automatically

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install requests
        run: pip install requests

      - name: Run hash check
        run: python job.py

      - name: Commit updated hash.txt
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add hash.txt
          git diff-index --quiet HEAD || git commit -m "Update hash.txt"
          git push